export const questions = [
    {
        id: 'nombre',
        label: '1. Nombre completo',
        type: 'text',
        required: true,
    },
    {
        id: 'empresa',
        label: '2. Empresa u organización',
        type: 'text',
        required: true,
    },
    {
        id: 'cargo',
        label: '3. Cargo o puesto',
        type: 'text',
        required: true,
    },
    {
        id: 'email',
        label: '4. Correo electrónico',
        type: 'email',
        required: true,
    },
    {
        id: 'telefono',
        label: '5. Teléfono de contacto',
        type: 'tel',
        required: true,
    },
    {
        id: 'sector',
        label: '6. ¿Cuál es su sector industrial?',
        type: 'select',
        options: ['Minería', 'Construcción', 'Manufactura', 
            'Agro-industria', 'Comercio', 'Servicios', 'Otro'],
        required: true,
    },
    {
        id: 'interes_solar',
        label: '7. ¿Está interesado en soluciones de energía solar para su empresa?',
        type: 'radio',
        options: ['Sí, tengo interés inmediato', 
            'Sí, para el mediano plazo', 
            'Estoy evaluando opciones', 
            'No por el momento'],
        required: true,
    },
    {
        id: 'consumo',
        label: '8. ¿Cuál es el consumo energético mensual aproximado de su empresa?',
        type: 'select',
        options: ['Menos de 10,000 kWh', 
            '10,000 – 50,000 kWh', 
            '50,000 – 200,000 kWh', 
            'Más de 200,000 kWh', 
            'No lo sé'],
        required: true,
    },
    {
        id: 'renovables',
        label: '9. ¿Ha implementado o evaluado alguna solución de energía renovable anteriormente?',
        type: 'radio',
        options: ['Sí, ya tenemos instalaciones', 
            'Sí, lo hemos evaluado', 
            'No, pero nos interesa', 
            'No hemos considerado aún'],
        required: true,
    },
    {
        id: 'propuesta',
        label: '10. ¿Le gustaría recibir una propuesta personalizada de TEC Energy Solutions?',
        type: 'radio',
        options: ['Sí, con urgencia', 
            'Sí, en los próximos 30 días', 
            'Quizás más adelante', 
            'Solo quiero información general'],
        required: true,
    },
]